name: Build and Push to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate environment variables
        run: |
          chmod +x ./generate-env.sh
          ./generate-env.sh
        env:
          GITHUB_ENV: $GITHUB_ENV
          GITHUB_SHA: ${{ github.sha }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          build-args: |
            YQ_VERSION=${{ env.YQ_VERSION }}
            HELM_VERSION=${{ env.HELM_VERSION }}
            YTT_VERSION=${{ env.YTT_VERSION }}
            KAPP_VERSION=${{ env.KAPP_VERSION }}
            KCTRL_VERSION=${{ env.KCTRL_VERSION }}
            KBLD_VERSION=${{ env.KBLD_VERSION }}
            IMGPKG_VERSION=${{ env.IMGPKG_VERSION }}
            VENDIR_VERSION=${{ env.VENDIR_VERSION }}
            K9S_VERSION=${{ env.K9S_VERSION }}
            TANZU_CLI_VERSION=${{ env.TANZU_CLI_VERSION }}
            VELERO_VERSION=${{ env.VELERO_VERSION }}
            KUBECTL_VERSION=${{ env.KUBECTL_VERSION }}
            IMAGE_VERSION=${{ env.IMAGE_VERSION }}
